### ISSUE TITLE
Quantity Input default styles are displaying

### ISSUE THREAD

**Issue by caitlynmayers** [caitlynmayers/dukes#11]
### Location
Products - http://dev-dukes.pantheonsite.io/product/light-mayonnaise/

### Description
The quantity input is displaying the default styles.

### Current Results
<img width="273" alt="screen shot 2016-11-18 at 12 59 13 pm" src="https://cloud.githubusercontent.com/assets/1574420/20440691/192d270e-ad8f-11e6-89dc-27098d20f53c.png">

**Comment by hessdev** [comment]
Why is this a bug?

**Comment by caitlynmayers** [comment]
@hessdev because it is confusing to users as to how they should interact with this input. We should either use the default styles or use the + / -. @kimberlydenham how was this designed?

**Comment by caitlynmayers** [comment]
Controls disabled until hover, which is adequate. Fix verified.
