### ISSUE TITLE
Add Instagram icon to social share regions

### ISSUE THREAD

**Issue by caitlynmayers** [caitlynmayers/dukes#111]
### Location
Footer
All recipe pages - http://test-dukes.pantheonsite.io/recipe/alabama-collard-greens-pizza/

### Description
Add the Instagram icon to the recipe single template and footer Connect w/ Us areas.

**Comment by hessdev** [comment]
AddThis does not have an Instagram sharing button.

**Comment by caitlynmayers** [comment]
@tbjor3zs we cannot complete this task using AddThis, which is the current social share service we are using. If they want instagram, it will make things a little complicated to add that, so I say we should shelve this for post-launch.

**Comment by tbjor3zs** [comment]
Already discussed with them. Good call!

Travis Bjorklund
Phone: 804.928.7337

________________________________

**Comment by caitlynmayers** [comment]
Verified.
