### ISSUE TITLE
Line through search results in certain searches

### ISSUE THREAD

**Issue by tbjor3zs** [caitlynmayers/dukes#119]
### Location
http://test-dukes.pantheonsite.io/?post_type=product&s=potato+salad

### Description

When you search "potato salad" from the main search and then filter to "products," you get a line through the description of the product.

### Current Results

![image](https://cloud.githubusercontent.com/assets/23704537/21060505/b420f010-be15-11e6-82fa-2ee5967a14e8.png)

#### Steps to Replicate

**Comment by caitlynmayers** [comment]
Fix verified.
