### ISSUE TITLE
Adjust Navigation dimensions

### ISSUE THREAD

**Issue by caitlynmayers** [caitlynmayers/dukes#2]
### Location
Header - http://dev-dukes.pantheonsite.io/

### Description
The navigation dimensions are not to desired spec - please revise to match specs below.

### Current Results
<img width="436" alt="screen shot 2016-11-18 at 11 16 09 am" src="https://cloud.githubusercontent.com/assets/1574420/20437021/6e320a3a-ad80-11e6-8d24-3b567870e79e.png">

### Expected Results
<img width="359" alt="screen_shot_2016-11-17_at_1 19 15_pm" src="https://cloud.githubusercontent.com/assets/1574420/20437033/78fcbe2e-ad80-11e6-962a-b26f052396b0.png">

**Comment by caitlynmayers** [comment]
@kimberlydenham can you confirm this update is correct?

**Comment by kimberlydenham** [comment]
Fix verified.
