### ISSUE TITLE
Duke's Logo Height Incorrect

### ISSUE THREAD

**Issue by kimberlydenham** [caitlynmayers/dukes#43]
### Location
Navigation on all pages

### Description
Adjust height of logo on site to exact proportion to that of logo in assets library. Check note on Assets: Buttons, Dropdown & Hover

### Current Results
<img width="227" alt="screen shot 2016-11-23 at 10 29 54 am" src="https://cloud.githubusercontent.com/assets/5461099/20567725/d346158e-b167-11e6-86d3-411b726e8891.png">

### Expected Results
<img width="427" alt="screen shot 2016-11-23 at 10 31 04 am" src="https://cloud.githubusercontent.com/assets/5461099/20567770/004d56d2-b168-11e6-879b-354a08f599e5.png">

#### Steps to Replicate
Use logo in assets library.

**Comment by caitlynmayers** [comment]
@kimberlydenham is this good to go?

**Comment by caitlynmayers** [comment]
Fix verified.
