### ISSUE TITLE
Contact Us Form does not match requirements

### ISSUE THREAD

**Issue by tbjor3zs** [caitlynmayers/dukes#44]
### Location
http://dev-dukes.pantheonsite.io/news/contact-us/

### Description
Contact form should have another choice for "type of inquiry" that drives the rest of the boxes and whoever gets the email.

### Current Results
Form is standard.

### Expected Results
![image](https://cloud.githubusercontent.com/assets/23704537/20570783/ff7329fc-b172-11e6-8f7e-28958cb1b88e.png)

All emails should continue to be sent to consumer-information@cfsauer.com.  I’ve noted below additional email addresses to include for each category.
-          General Inquiry
-          Comments and Stories + lferber@cfsauer.com, ccreasey@cfsauer.com 
-          Submit a Recipe + lferber@cfsauer.com, ccreasey@cfsauer.com
-          Product Quality
Required info:
o   Lot Code
o   Best by date
o   UPC
o   Where purchased
-          Donation and Sponsorship Requests + lferber@cfsauer.com, ccreasey@cfsauer.com

**Comment by caitlynmayers** [comment]
Added #96 to address remaining unaddressed items in this issue.
