### ISSUE TITLE
Newsletter section adjustments

### ISSUE THREAD

**Issue by kimberlydenham** [caitlynmayers/dukes#49]
### Location
Home page

### Description
missing background color behind text 

### Current Results
<img width="1390" alt="screen shot 2016-11-30 at 11 40 34 am" src="https://cloud.githubusercontent.com/assets/5461099/20761712/ddd8fe3c-b6f1-11e6-98fe-2eb09ca6e6a0.png">

### Expected Results
<img width="1125" alt="screen shot 2016-11-30 at 11 41 17 am" src="https://cloud.githubusercontent.com/assets/5461099/20761742/f7246610-b6f1-11e6-8936-7a2d69a48707.png">

#### Steps to Replicate
add background color white, please set sufficient padding via matching pixels in zeplin, as well as section height

**Comment by caitlynmayers** [comment]
Duplicate, fix verified.
