### ISSUE TITLE
Product Review Bug

### ISSUE THREAD

**Issue by tbjor3zs** [caitlynmayers/dukes#54]
### Location

http://test-dukes.pantheonsite.io/product/tartar-sauce/

### Description

The behavior exactly after submitting a comment is unusual--the screen bounces around and eventually settles on the top of reloaded page, which feels odd. It would be more intuitive if the page either didn't reload at all or if it reloaded to the comment just added. 

#### Steps to Replicate

Add a product review on any product and click "submit"

**Comment by caitlynmayers** [comment]
I am still seeing this.

**Comment by caitlynmayers** [comment]
Fix verified.
