### ISSUE TITLE
Can't see number on Merchandise Quantity

### ISSUE THREAD

**Issue by tbjor3zs** [caitlynmayers/dukes#55]
### Location
http://dev-dukes.pantheonsite.io/product/dukes-t-shirt/

### Description

When you try and change the quantity you can't see the the numbers

### Current Results

![image](https://cloud.githubusercontent.com/assets/23704537/20775153/901e2fa6-b727-11e6-800a-8b2c37a5638f.png)

#### Steps to Replicate

**Comment by caitlynmayers** [comment]
Fix verified.
