### ISSUE TITLE
Sizes not appearing on shirts

### ISSUE THREAD

**Issue by tbjor3zs** [caitlynmayers/dukes#56]
### Location

http://dev-dukes.pantheonsite.io/product/dukes-mayonnaise-logo-polo-shirt-white/
### Description

I've added sizes in the CMS, but they are not appearing on the site. 
### Current Results

![image](https://cloud.githubusercontent.com/assets/23704537/20775638/ff839474-b729-11e6-9b17-51749a12cbc7.png)

#### Steps to Replicate

**Comment by caitlynmayers** [comment]
Fix verified.
