### ISSUE TITLE
Medal appears over modal

### ISSUE THREAD

**Issue by tbjor3zs** [caitlynmayers/dukes#57]
### Location

http://test-dukes.pantheonsite.io/stories/customers/
### Description
When you click "submit story," a modal pops up, but the duke's medallion sits over it. 

### Current Results

![image](https://cloud.githubusercontent.com/assets/23704537/20776615/b5f4a806-b72f-11e6-9050-9de713040543.png)

#### Steps to Replicate

**Comment by caitlynmayers** [comment]
Fix verified.
