### ISSUE TITLE
"Related" Sections: Product Recipes

### ISSUE THREAD

**Issue by kimberlydenham** [caitlynmayers/dukes#58]
### Location
Bottom of all individual product pages

### Description
Update the copy for the related recipe sections on the product pages to read "Duke's Recipes" 

### Current Results
<img width="1066" alt="screen shot 2016-12-01 at 1 04 28 pm" src="https://cloud.githubusercontent.com/assets/5461099/20805918/bae448b6-b7c6-11e6-853f-f033daad22a7.png">

### Expected Results
<img width="1199" alt="screen shot 2016-12-01 at 12 57 35 pm" src="https://cloud.githubusercontent.com/assets/5461099/20805897/a15ecc4a-b7c6-11e6-99ef-1869bf8c6c99.png">

#### Steps to Replicate

**Comment by caitlynmayers** [comment]
Fix verified.
