### ISSUE TITLE
Bottom Bar on home page is off-center and text is hard to read (add white background)

### ISSUE THREAD

**Issue by tbjor3zs** [caitlynmayers/dukes#60]
### Location
http://test-dukes.pantheonsite.io/#

### Current Results
![image](https://cloud.githubusercontent.com/assets/23704537/20807360/904ea668-b7cc-11e6-8c25-fa25a8f0fb24.png)

#### Steps to Replicate

**Comment by caitlynmayers** [comment]
Fix verified.
