### ISSUE TITLE
Quantity (the word) on product page is in the wrong place (should be after the price)

### ISSUE THREAD

**Issue by tbjor3zs** [caitlynmayers/dukes#62]
### Location
http://test-dukes.pantheonsite.io/product/real-mayonnaise/

### Description
After an item is selected and the price is populated, the price displays beneath the Quantity heading and input. The price should not separate the two.

### Current Results
![image](https://cloud.githubusercontent.com/assets/23704537/20807655/d118fbde-b7cd-11e6-904e-5c1ac7cc09c3.png)

**Comment by hessdev** [comment]
Per our discussion, It's not possible to move the price between the quantity and the 'Add to Cart' button.
