### ISSUE TITLE
Hover over on "quantity" number shows an extra quantity selector

### ISSUE THREAD

**Issue by tbjor3zs** [caitlynmayers/dukes#63]
### Location
http://test-dukes.pantheonsite.io/product/light-mayonnaise/

### Current Results

![image](https://cloud.githubusercontent.com/assets/23704537/20808233/d48db2d0-b7cf-11e6-829e-955d52b11633.png)

#### Steps to Replicate

**Comment by hessdev** [comment]
Woocommerce creates the quantity field as a"number" field, so the browser adds the up and down arrows automatically. This cannot be changed.
