### ISSUE TITLE
Merchandise: Button Color

### ISSUE THREAD

**Issue by jasonpoulos** [caitlynmayers/dukes#64]
http://test-dukes.pantheonsite.io/product/dukes-mayonnaise-logo-baseball-cap/

Purple button doesn't match red buttons on site
<img width="718" alt="screen shot 2016-12-01 at 3 02 59 pm" src="https://cloud.githubusercontent.com/assets/24302252/20810366/752f5ce6-b7d7-11e6-8437-a950a697a063.png">

**Comment by caitlynmayers** [comment]
Fix verified.
