### ISSUE TITLE
Merchandise: Text Wrap

### ISSUE THREAD

**Issue by jasonpoulos** [caitlynmayers/dukes#65]
http://test-dukes.pantheonsite.io/product/dukes-mayonnaise-logo-baseball-cap/

Merchandise item title overlaps curved element and image
<img width="354" alt="screen shot 2016-12-01 at 3 05 43 pm" src="https://cloud.githubusercontent.com/assets/24302252/20810412/ac1019c6-b7d7-11e6-8637-5f284cae4337.png">

**Comment by caitlynmayers** [comment]
Fix verified, duplicate bug.
