### ISSUE TITLE
Merchandise: Prices

### ISSUE THREAD

**Issue by jasonpoulos** [caitlynmayers/dukes#66]
All merchandise items are missing their prices. Is this a no content issue or is it not displaying because of a functional error?

<img width="390" alt="screen shot 2016-12-01 at 3 11 21 pm" src="https://cloud.githubusercontent.com/assets/24302252/20810640/72de0ff4-b7d8-11e6-8190-3e57d23129c0.png">

**Comment by caitlynmayers** [comment]
@hessdev we just chatted re: this - merchandise has pricing in the admin/woo but it isn't populating on the front end.

**Comment by caitlynmayers** [comment]
Fix verified.
