### ISSUE TITLE
Merchandise: View Cart Text Wrap

### ISSUE THREAD

**Issue by jasonpoulos** [caitlynmayers/dukes#69]
On all merch pages, when a item is added to the cart, "view cart" button overlaps header image

<img width="1184" alt="screen shot 2016-12-01 at 3 07 55 pm" src="https://cloud.githubusercontent.com/assets/24302252/20810877/83f10d04-b7d9-11e6-9b68-abed1a8e2123.png">

**Comment by caitlynmayers** [comment]
Modal implementation addresses this issue.
