### ISSUE TITLE
Merchandise: Button hover state

### ISSUE THREAD

**Issue by jasonpoulos** [caitlynmayers/dukes#70]
View cart button bg color goes to gray, other buttons (homepage) go to white
<img width="137" alt="screen shot 2016-12-01 at 3 20 51 pm" src="https://cloud.githubusercontent.com/assets/24302252/20811079/4a4f4592-b7da-11e6-9b89-5a4ed5825f80.png">

**Comment by caitlynmayers** [comment]
Fix verified - modal changes this interaction.
