### ISSUE TITLE
Merchandise: Quantity Button Wonky

### ISSUE THREAD

**Issue by jasonpoulos** [caitlynmayers/dukes#71]
Had trouble using the arrows to adjust quantity, typing in the number didn't show up either. Same issue is occuring in the shopping cart
<img width="134" alt="screen shot 2016-12-01 at 3 23 54 pm" src="https://cloud.githubusercontent.com/assets/24302252/20811198/c9e8d0ac-b7da-11e6-9452-853b46baa9c6.png">

**Comment by caitlynmayers** [comment]
Duplicate issue, closing.
