### ISSUE TITLE
Shopping Cart: Default Quantity

### ISSUE THREAD

**Issue by jasonpoulos** [caitlynmayers/dukes#72]
Default item quantities aren't showing up in the shopping cart
<img width="477" alt="screen shot 2016-12-01 at 3 29 28 pm" src="https://cloud.githubusercontent.com/assets/24302252/20811417/9a338b8a-b7db-11e6-91f5-ddedcaaa54a9.png">

**Comment by caitlynmayers** [comment]
Duplicate of #28.
