### ISSUE TITLE
Shopping Cart: Coupon & Update Buttons

### ISSUE THREAD

**Issue by jasonpoulos** [caitlynmayers/dukes#73]
This area feels a little cluttered, haven't seen the comp but maybe the "update cart" button should be in the far right of this field? Does there need to be an "apply coupon" button and a field for the coupon? Once entering the coupon code, wouldn't hitting "update cart" have the same function as "apply coupon"?
<img width="259" alt="screen shot 2016-12-01 at 3 37 32 pm" src="https://cloud.githubusercontent.com/assets/24302252/20811664/96d88ee4-b7dc-11e6-82a4-80152847ef53.png">

**Comment by caitlynmayers** [comment]
Duplicate issue.
