### ISSUE TITLE
Shopping Cart: Button Alignment

### ISSUE THREAD

**Issue by jasonpoulos** [caitlynmayers/dukes#74]
"Update cart" button is enclosed in the cart box, "proceed to checkout" is outside of the cart totals box. Both should probably use the same type of placement and styling.
<img width="400" alt="screen shot 2016-12-01 at 3 42 16 pm" src="https://cloud.githubusercontent.com/assets/24302252/20811814/1d8e60d0-b7dd-11e6-8339-1a81c9646358.png">

**Comment by caitlynmayers** [comment]
Duplicate #32.
