### ISSUE TITLE
product purchase page

### ISSUE THREAD

**Issue by kimberlydenham** [caitlynmayers/dukes#77]
### Description
request to make the price on the page look similar to that on the merchandise page. I think we need to explain the difference between the pages and why the price needs to be after the selection has been made. 

#### Steps to Replicate

**Comment by mbcaptech** [comment]
Kim - Please add a URL and page name to the above. :-)

**Comment by kimberlydenham** [comment]
Will do in the morning :)

**Comment by caitlynmayers** [comment]
This issue is unclear/doesn't seem to be an immediate blocker, so I'm flagging low priority and moving to the 1.1 milestone.

**Comment by caitlynmayers** [comment]
Closing per @kimberlydenham.
