### ISSUE TITLE
Merchandise pages missing reviews section

### ISSUE THREAD

**Issue by kimberlydenham** [caitlynmayers/dukes#79]
### Location
Merchandise Product Single - http://test-dukes.pantheonsite.io/product/dukes-mayonnaise-logo-polo-shirt-white/

### Description
The merchandise products are not displaying the reviews section.

### Current Results
<img width="979" alt="screen shot 2016-12-01 at 10 18 57 pm" src="https://cloud.githubusercontent.com/assets/5461099/20821858/310a0704-b814-11e6-8aa4-0f0e72e59c4c.png">

### Expected Results

<img width="401" alt="screen shot 2016-12-01 at 10 15 09 pm" src="https://cloud.githubusercontent.com/assets/5461099/20821862/3559e518-b814-11e6-8ced-be7dbdad89c6.png">

**Comment by caitlynmayers** [comment]
@tbjor3zs are the Merchandise products supposed to have reviews and related products?

**Comment by tbjor3zs** [comment]
They have reviews, no? I think they are technically supposed to have related products but that is low priority.

**Comment by caitlynmayers** [comment]
Fix verified.
