### ISSUE TITLE
navigation icon hover state 

### ISSUE THREAD

**Issue by kimberlydenham** [caitlynmayers/dukes#82]
### Location
all pages, viewport less than 1200 

### Description
sprite not tall enough for hover state. i'll make sure to add some space in the new icons. 

### Current Results

<img width="1144" alt="screen shot 2016-12-01 at 10 49 10 pm" src="https://cloud.githubusercontent.com/assets/5461099/20822443/b8d10774-b818-11e6-9c06-96bb73e9bcce.png">

#### Steps to Replicate

**Comment by caitlynmayers** [comment]
Fix verified.
