### ISSUE TITLE
Contact Us Template Content Changes

### ISSUE THREAD

**Issue by kimberlydenham** [caitlynmayers/dukes#83]
### Location
http://test-dukes.pantheonsite.io/news/contact-us/

### Description
1. Change page h1 to Contact Us
2. Remove page h3 (Contact Us) from template
3. Remove By Email section from template
4. In the By Mail section, add The before C.F. Sauer Company so it reads The C.F. Sauer Company
5. Remove the By Mail and By Telephone headings.

**Comment by caitlynmayers** [comment]
@hessdev if you can do 4 in the list above, this issue will be complete.

**Comment by caitlynmayers** [comment]
@hessdev have you pushed this? Not seeing it here http://test-dukes.pantheonsite.io/news/contact-us/

**Comment by caitlynmayers** [comment]
Fix verified.
