### ISSUE TITLE
Navigation dropdown order

### ISSUE THREAD

**Issue by kimberlydenham** [caitlynmayers/dukes#84]
### Location
Stories dropdown menu on hover, News & Events dropdown

### Description
the order of the links should match the order they are in on the landing page. 

### Current Results

<img width="1132" alt="screen shot 2016-12-01 at 10 56 29 pm" src="https://cloud.githubusercontent.com/assets/5461099/20822576/bbf8a3c0-b819-11e6-903b-9c0b72d0941f.png">

#### Steps to Replicate

**Comment by caitlynmayers** [comment]
Change made by me in CMS and verified.
