### ISSUE TITLE
Dropdown missing on "Where to Buy"

### ISSUE THREAD

**Issue by kimberlydenham** [caitlynmayers/dukes#85]
### Location
All- in navigation

### Description
dropdown should read "store locator" and "Buy Duke's Online"

### Expected Results
<img width="1258" alt="screen shot 2016-12-01 at 11 00 18 pm" src="https://cloud.githubusercontent.com/assets/5461099/20822610/1696035e-b81a-11e6-82a1-1cff17e4a24d.png">

#### Steps to Replicate

**Comment by caitlynmayers** [comment]
Client changed request and do not want this.
