### ISSUE TITLE
Change default copy of Events template if no posts

### ISSUE THREAD

**Issue by tbjor3zs** [caitlynmayers/dukes#86]
### Location
http://test-dukes.pantheonsite.io/category/event/

### Description
Change the No posts were found text to "There are no events scheduled at the moment. Check back later to find Duke's events near you."

### Current Results
![image](https://cloud.githubusercontent.com/assets/23704537/20830759/0c1f887e-b850-11e6-8cdb-dfe0b15fadde.png)

**Comment by caitlynmayers** [comment]
Fix verified.
