### ISSUE TITLE
Hat Merchandise Quantity selector doesn't match and text runs over

### ISSUE THREAD

**Issue by tbjor3zs** [caitlynmayers/dukes#87]
### Location
http://test-dukes.pantheonsite.io/product/dukes-mayonnaise-logo-baseball-cap/

### Description
Also, is the button supposed to be Purple?

### Current Results
![image](https://cloud.githubusercontent.com/assets/23704537/20831731/75862dfa-b854-11e6-8c27-ed5db0f9c273.png)

#### Steps to Replicate

**Comment by caitlynmayers** [comment]
The description is unclear and appears to have been addressed.
