### ISSUE TITLE
More Chefs Section

### ISSUE THREAD

**Issue by kimberlydenham** [caitlynmayers/dukes#92]
### Location
"Favorite Chefs" former "Chefs Tell All" Page

### Description
Change text to read "More Chefs"

### Current Results
<img width="1219" alt="screen shot 2016-12-02 at 10 33 56 am" src="https://cloud.githubusercontent.com/assets/5461099/20839529/00564e30-b87b-11e6-9eb5-11391dbf7779.png">

#### Steps to Replicate

**Comment by caitlynmayers** [comment]
Fix verified.
