### ISSUE TITLE
Many of the headers go under the top nav in chrome

### ISSUE THREAD

**Issue by tbjor3zs** [caitlynmayers/dukes#93]
### Location

Here's just one example: http://test-dukes.pantheonsite.io/recipes/?course=desserts-breads

### Current Results
![image](https://cloud.githubusercontent.com/assets/23704537/20860678/a718547c-b94b-11e6-94c7-475d0d769be9.png)

#### Steps to Replicate

**Comment by caitlynmayers** [comment]
Fix verified.
